# Generated by Django 2.0.4 on 2018-05-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_color_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='image',
        ),
        migrations.AddField(
            model_name='color',
            name='css_color',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
