# Generated by Django 2.0.4 on 2018-05-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180502_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('img', models.ImageField(blank=True, upload_to='products/shop/media/image_product/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(to='shop.Image_product'),
        ),
    ]
