# Generated by Django 2.0.4 on 2018-05-06 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180503_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_product',
            name='name',
        ),
    ]
