# Generated by Django 2.0.4 on 2018-05-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_dog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
