# Generated by Django 2.0.4 on 2018-05-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_delete_dog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='detail_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='detail',
            new_name='short_description',
        ),
    ]
