# Generated by Django 2.0.4 on 2018-05-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20180512_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('CROMIA', 'Cromia'), ('RIPANI', 'Ripani'), ('TOSCA BLU', 'Tosca Blu'), ('ELEGANZZA', 'Eleganzza')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
