# Generated by Django 2.0.4 on 2018-05-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20180513_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('CROMIA', 'Cromia'), ('RIPANI', 'Ripani'), ('TOSCA BLU', 'Tosca Blu'), ('ELEGANZZA', 'Eleganzza')], max_length=100),
        ),
    ]
