# Generated by Django 2.0.4 on 2018-05-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20180513_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_test',
            field=models.CharField(choices=[('Красный', '100'), ('Синий', '200'), ('Черный', '300'), ('Зеленый', '400')], default='Красный', max_length=100),
        ),
    ]
