# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 23:22
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0010_auto_20180414_2058'),
        ('shop', '0019_auto_20180513_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='testq',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File'),
        ),
    ]
