# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_category_testq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='testq',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
